### ISSUE TITLE
Add an "engines" entry in the package.json saying that this only supports Node.js version 5 and higher

### ISSUE THREAD

**Issue by christianbundy** [ssb-js/secret-stack#50]
> But before, could you add an "engines" entry in the package.json saying that this only supports Node.js version 5 and higher?

We should do this. Maybe in this PR or after.

_Originally posted by @staltz in https://github.com/ssbc/secret-stack/pull/45#issuecomment-556006352_

**Comment by staltz** [comment]
STAAAAAAAAAAAAAAAAP

**Comment by staltz** [comment]
Done as of #54
