### ISSUE TITLE
fails when config.connections.incoming.net[].external is array (as is documented)

### ISSUE THREAD

**Issue by ahdinosaur** [ssb-js/secret-stack#62]
hallo! :smiley_cat: 

i just ran into an error after upgrading [`ssb-pub`](https://github.com/ahdinosaur/ssb-pub) to a less broken version of `ssb-server`: https://github.com/ahdinosaur/ssb-pub/issues/37

when running `sbot invite.create 1`, i get the error:

```
/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:123
      throw err
      ^
{
  message: 'resultHost.replace is not a function',
  name: 'TypeError',
  stack: 'TypeError: resultHost.replace is not a function\n' +
    '    at Object.stringify (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/multiserver/plugins/net.js:124:31)\n' +
    '    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/multiserver/compose.js:111:19\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at Object.stringify (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/multiserver/compose.js:110:22)\n' +
    '    at /home/node/.npm-global/lib/node_modules/ssb-server/node_modules/multiserver/index.js:67:44\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at Object.stringify (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/multiserver/index.js:67:10)\n' +
    '    at EventEmitter.getAddress (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/secret-stack/core.js:213:21)\n' +
    '    at EventEmitter.hooked [as getAddress] (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/hoox/index.js:10:15)\n' +
    '    at getInviteAddress (/home/node/.npm-global/lib/node_modules/ssb-server/node_modules/ssb-invite/index.js:75:18)'
}
```

investigating, i see that it's an issue with `secret-stack` (and maybe other modules too), not working when `config.connections.incoming.net[].external` is an array of strings, as is documented in [ssb-config#connections](https://github.com/ssbc/ssb-config#connections).

i changed the config to be a single string, and this works. but was this breaking change on purpose?

for what it's worth, i'm very excited to see y'all transitioning the code base to TypeScript. seems like every time i try to upgrade anything i run into multiple undocumented breaking changes, so hopefully being more explicit about types will help us here, y'all are doing the lord's work, so to speak. :purple_heart: :+1:

**Comment by staltz** [comment]
Hey @ahdinosaur nice that you appreciate the TypeScript. When migrating from JS to TS I took extra care to *not* introduce breaking changes, but it's possible that a breaking change slipped through. But I don't see in this codebase the treatment of `external` at all, not before TS and not after, either.

I think the treatment of `external` and the erroneous use of `.replace` is in multiserver instead: https://github.com/ssb-js/multiserver/blob/7d47892757c14732b47662d81e36dd21f3c16b6b/plugins/net.js#L115-L124

**Comment by staltz** [comment]
@ahdinosaur I suspect multiserver never actually supported `external` being an array of strings. At least I can't see in the recent past (i.e. 2 years) it handling arrays as a possibility. ssb-config's README claims that it can be an array of strings, but ssb-config itself doesn't have any code related to `external` at all. So instead of going down the path of adding support for an array of strings, I'd recommend just using string directly, and then we should update the README in ssb-config.

**Comment by ahdinosaur** [comment]
> When migrating from JS to TS I took extra care to _not_ introduce breaking changes, but it's possible that a breaking change slipped through.

sorry, i should have mentioned this is using `secret-stack@6.3.1`, so before the TypeScript conversion.

> I think the treatment of `external` and the erroneous use of `.replace` is in multiserver instead: https://github.com/ssb-js/multiserver/blob/7d47892757c14732b47662d81e36dd21f3c16b6b/plugins/net.js#L115-L124

oops, you're totally right. i was looking at the `multiserver/plugins/net.js` code, so i'm not actually sure why i made the issue here. anyways, thanks for forwarding along! :purple_heart:
