### ISSUE TITLE
travis testing wrong node versions

### ISSUE THREAD

**Issue by christianbundy** [ssb-js/secret-stack#64]
looks like it's currently 6 + 8 + 10 but I don't think we want to support 6

**Comment by staltz** [comment]
yeah. ever since github actions has launched my travis dashboard has been totally bugged, i can't add any new repos or anything, so i've been using github actions. (i wonder what happened!)

i agree we should bump up the supported versions. 10+12+14 sounds good

**Comment by christianbundy** [comment]
I know I had something similar when they switched from travis.org to travis.com, any chance that's the problem? I've been going to travis.com and it's been un-broken.

**Comment by staltz** [comment]
This is what travis.com looks to me:

![Screenshot from 2020-11-18 19-44-50](https://user-images.githubusercontent.com/90512/99567211-92595400-29d6-11eb-870f-01592a9da844.png)

**Comment by christianbundy** [comment]
lol oops, travis-ci.com?

**Comment by staltz** [comment]
mmm! maybe that is working now!

**Comment by staltz** [comment]
Done, it seems?
